### ISSUE TITLE
@kadena/client: Provide a convenient way to sign a transaction with a keypair

### ISSUE THREAD

**Issue by CryptoPascal31** [kadena-community/kadena.js#781]
### Please confirm the following:

- [X] I have read the [Code of Conduct](https://github.com/kadena-community/kadena.js/blob/main/CODE_OF_CONDUCT.md)
- [X] The feature was not suggested before

### Is your feature request related to a problem?

AFAIK (I may be wrong), there is to convenient way to sign a transaction directly with a key pair.

Currently it is very simple to sign with chainweaver or walletConnect. 
But nothing seems to be provided to do a basic signature with a "just generated" key or loaded key from disk.

### Describe the solution you'd like

A would like to have a simple function like:

```javascript
signWithKeyPair(my-transaction, my-key)
```
where `my-transaction` is created by ```.createTransaction()```
and my-key is an ```IKeyPair```

Moreover it looks like that the ```addSignatures()``` function has been made private.

### Describe alternatives you've considered

I currently use this workaround:

```javascript
      const trx = cmd.createTransaction()
      trx.sigs[0] = signHash(trx.hash, key_1);
      trx.sigs[1] = signHash(trx.hash, key_2);
```
IMO, this "low-level" code should be managed by the @kadena/client lib, not by the user himself.

And there is a big drawback: this doesn't use the magic of ```addSignatures()```, which manages automatically the order of the signatures. And I have to ensure manually that I insert each signature exactly in the same order as the signers in the transaction payload.

### Participation

- [ ] I am willing to submit a pull request for this feature request.

**Comment by alber70g** [comment]
We strongly discourage the creation of interfaces that require users to submit private keys. The decision to omit the `signWithKeyPair` function was made deliberately. 

However, we have [made the `addSignatures` function public](#791) to accommodate custom flows and provide flexibility.

**Comment by CryptoPascal31** [comment]
Understand your answer. 

But there are many use cases that would justify to directly sign with a private key, and not a wallet

The most obvious case is when working in back-end, with private keys are kept private and securely stored by the backend. 

But this would be needed as well in frontends. There are many use cases with Kadena, where temporary keys are needed to sign transactions:
   - For example to trigger a gas station that makes usage of the GAS_PAYER interface.

**Comment by trendzetter** [comment]
I have to agree here that the wallets only option that appears to have been chosen is seriously complicating automated deployments or learning scenario's in testnet. I looked at the election app tutorial and all relatively easy to get started until it starts requiring chainweaver.
Imo kadena.js is making the opposite error of pact-lang-api, its a form of extremism as well. While pact-lang-api forced you to use plain text keys even when its not needed, kadena.js is doing away with an essential tool.

**Comment by alber70g** [comment]
@CryptoPascal31 @trendzetter 
What do you think of exposing a `signWithKeypair` from `@kadena/cryptography-utils`?

**Comment by CryptoPascal31** [comment]
IMHO, it should be in @kadena/client:
  - signWithChainweaver
  - signWithWalletConnect
  - signWithEckoWallet
  
and .... :
  - signWithKeypair

At the same level of the other signature methods. No ? Looks consistent...

**Comment by LindaOrtega** [comment]
We'll add to our backlog a function that allows users to sign with a private key (and takes care of making sure the signatures are in the correct order).

@CryptoPascal31 @trendzetter are there any other functions that we should add to kadena/client that would make it easier to do automations and learning?

**Comment by trendzetter** [comment]
That sounds good to me. Like it is now I don't think its technically hard to work-around for experienced developers who have some in-depth knowledge about Kadena, its might just be somewhat discouraging for new adopters.
The most important matter is in explaining a recommended workflow.
1. for learning without a high entrance barriers for new people. So given the example above of the election tutorial. People will be more likely to complete the tutorial if they don't have to load virtual machines just to try a language tutorial.
2. for production setups I think scripted deploys are actually recommended because it increases consistency and continuous integration.
Of course it will need some stressing of the importance to keep your production keys secure, eg on an encrypted partition with decent backup regime, only mounted from an operating system that is kept secure and is not used for various purposes such as browsing and email to avoid phishing risks etc.. I see why want to encourage encrypted storage of keys and suggest people to use wallets for signing. But you can never totally assure safe behavior by design. People can always use risky behavior even if you require them to use wallets to store their keys. eg They can store their password in plain text or keep a remote desktop session open day and night.

**Comment by alber70g** [comment]
@trendzetter @CryptoPascal31 could you check this PR and see if this fits your needs? https://github.com/kadena-community/kadena.js/pull/913

**Comment by CryptoPascal31** [comment]
@alber70g => Great.

I'm closing the issue
